export enum Category {
    music = "music",
    info = "info",
    dev = "dev",
    filters = "filters",
    playlist = "playlist",
    admin = "admin",
}

export enum Mode {
    production = "production",
    development = "development",
    test = "test",
}

export enum Language {
    // Bulgarian = "Bulgarian",
    // ChineseCN = 'ChineseCN',
    // ChineseTW = 'ChineseTW',
    // Croatian = "Croatian",
    // Czech = "Czech",
    // Danish = "Danish",
    // Dutch = "Dutch",
    // EnglishGB = "EnglishGB",
    EnglishUS = "EnglishUS",
    // Finnish = "Finnish",
    // French = 'French',
    // German = 'German',
    // Greek = "Greek",
    // Hindi = 'Hindi',
    // Hungarian = "Hungarian",
    Indonesian = "Indonesian",
    // Italian = "Italian",
    Japanese = "Japanese",
    Korean = "Korean",
    // Lithuanian = "Lithuanian",
    // Norwegian = 'Norwegian',
    // Polish = 'Polish',
    // PortugueseBR = "PortugueseBR",
    // Romanian = "Romanian",
    // Russian = 'Russian',
    // SpanishES = 'SpanishES',
    // Swedish = "Swedish",
    // Thai = "Thai",
    // Turkish = "Turkish",
    // Ukrainian = "Ukrainian",
    Vietnamese = "Vietnamese",
}
